routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');

Route::get('/admin', function(){
	return view('Admin.index');
});
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController');
Route::resource('Admin/ProjectList','Admin\ProjectListController');
Route::resource('Admin/Services','Admin\ServicesController');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController');
Route::resource('Admin/Contact','Admin\ContactController');
Route::resource('Admin/Gallary','Admin\GallaryController');
Route::resource('Admin/MyCline','Admin\ContactUserController');
 

app/Http/Controllers/Admin/ServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\Service;
use Image;
use DB;

class ServicesController extends Controller
{
        public function index(){
    	$Services=Service::all();

       return view('Admin.Services.index')->with('Service',$Services);
    }
    public function create(){
    	return view('Admin.Services.create');
    }
    public function store(Request $request){
    	$Service =new Service;


    	$Service->category=$request->category;
    	$Service->subcategory=$request->subcategory;
    	$Service->title=$request->title;
    	$Service->description=$request->description;



    		if ($request->hasFile('photo')) {

            $file=$request->file('photo');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $Service->photo=$file_name;
        }

    		if ($request->hasFile('file')) {

            $file=$request->file('file');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            $file->move($location, $file_name);
            $Service->file=$file_name;
        }


        $Service->save();
       
       $Services=Service::all();

       return view('Admin.Services.index')->with('Service',$Services);

    }
    public function show($id){

    	$service= DB::table('services')->find($id);

    	return view('Admin.Services.show')->with('services', $service);
    }
    public function edit($id){
    	$service= DB::table('services')->find($id);

    	return view('Admin.Services.edit')->with('services', $service);
    }
    public function update(Request $request, $id){

    	$updateData=Service::find($id);

    	$updateData->category=$request->input('category');
    	$updateData->subcategory=$request->input('subcategory');
    	$updateData->title=$request->input('title');
    	$updateData->description=$request->input('description');


    		if ($request->hasFile('photo')) {

            $file=$request->file('photo');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $updateData->photo=$file_name;
        }

    		if ($request->hasFile('file')) {

            $file=$request->file('file');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            $file->move($location, $file_name);
            $updateData->file=$file_name;
        }

        $updateData->save();
         $Services=Service::all();

       return view('Admin.Services.index')->with('Service',$Services);
    }
    public function destroy($id)
    {
        $Services = Service::find($id);

        $Services->delete();

       $Services=Service::all();

       return view('Admin.Services.index')->with('Service',$Services);
    }
}

resources/views/Admin/Services/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/Services/create.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE SERVICE </h1>
		</div>
	</div>

<form class="form" action="{{route('Services.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Service Title</label>
			<input type="text" name="title" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Category</label>
			<input type="text" name="category" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Sub Catrgory</label>
			<input type="text" name="subcategory" class="form-control" required>
		<div class="help-block"></div>
		<div class="form-group">
			<spam>Description</spam>
			<textarea name="description" class="form-control" id="description" required></textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Cover Image</label>
			<input type="file" name="photo" class="form-control" required>
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">File</label>
			<input type="file" name="file" class="form-control" required>
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Services/edit.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT SERVICE </h1>
		</div>
	</div>

<form class="form" action="{{route('Services.update', [$services->id])}} " method="POST" enctype="multipart/form-data">
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Service Title</label>
			<input type="text" name="title" class="form-control" value="{{$services->title}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Category</label>
			<input type="text" name="category" class="form-control" value="{{$services->category}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Sub Catrgory</label>
			<input type="text" name="subcategory" class="form-control" value="{{$services->subcategory}}" required>
		<div class="help-block"></div>
		<div class="form-group">
			<spam>Description</spam>
			<textarea name="description" class="form-control" id="description" required>
				{{$services->description}}
			</textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Cover Image</label>
			<?php $url=url('image/'.$services->photo); 
                                ?>
			<input type="file" name="photo" class="form-control" value="{{$services->photo}}" >
			<img src="{{$url}}" height="100px" width="100px">
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">File</label>
			<input type="file" name="file" class="form-control" value="{{$services->file}}">
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Services/index.blade.php
@extends('Admin.About.base')

@section('action-content')
<div class="row">
	<div class="col-lg-12">
		<table class="table">
			<tr>
				<td>Sn</td>
				<td>Project Name</td>
				<td>Action</td>
				<td>
					<a href="{{route('Services.create')}}"  class="btn btn-primary btn-xm">Create</a>
				</td>
			</tr>
			@foreach($Service as $Services)
			<tr>

				<td>{{$Services->id}}</td>
				<td>{{$Services->title}}</td>
				<td><a href="{{route('Services.show',$Services->id )}}" class="btn btn-outline-info btn-sm" style="margin-right: 20px;">View</a>
					<a href="{{route('Services.edit',$Services->id )}}" class="btn btn-outline-success btn-sm" style="margin-right: 20px;">Edit</a>
				</td>
			</tr>
			@endforeach
		</table>
	</div>
	
</div>

@endsection

resources/views/Admin/Services/show.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="adminAbout">
	<table class="table">
		<tr>
			<td>Name</td>
			<td>{{$services->title}}</td>
		</tr>
			<td>Project Category</td>
			<td>{{$services->category}}</td>
		</tr>
			<td>Project Sub Category</td>
			<td>{{$services->subcategory}}</td>
		</tr>
		<tr>
			<td>Description</td>
			<td>{!!$services->description!!} </td>
		</tr>
				<tr>
			<td>Cover Image</td>
			<?php $url=url('image/'.$services->photo); 
                                ?>
			<td> <img src="{{$url}}" height="200px" width="200px"></td>
		</tr>
		<tr>
			<td><a href="{{route('Services.edit', $services->id)}}"  class="btn btn-success">Edit</a></td>
			<td>


<form action="{{route('Services.destroy', [$services->id])}}" method="POST">
    		<input type="hidden" name="_method" value="DELETE">
   		<input type="hidden" name="_token" value="{{ csrf_token() }}">
   		<input type="submit" class="btn btn-danger" value="Delete"/>
</form>
			
		</tr>
		
	</table>
</div>
@endsection