routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');

Route::get('/admin', function(){
	return view('Admin.index');
});
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController');
Route::resource('Admin/ProjectList','Admin\ProjectListController');
Route::resource('Admin/Services','Admin\ServicesController');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController');
Route::resource('Admin/Contact','Admin\ContactController');
Route::resource('Admin/Gallary','Admin\GallaryController');
Route::resource('Admin/MyCline','Admin\ContactUserController');
 

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\Contact;

class ContactController extends Controller
{
	

    public function index(){

    	$contact=Contact::all();

    	return view('Admin.Contact.index')->with('contact', $contact);
    }
    public function create(){

    	return view('Admin.Contact.create');
    }
    public function store(Request $request){

    	$contacts=new Contact;
    	$contacts->name=$request->name;
    	$contacts->address=$request->address;
    	$contacts->zipcode=$request->zipcode;
    	$contacts->postboxnumber=$request->postboxnumber;
    	$contacts->pannumber=$request->pannumber;
    	$contacts->mobilenumber=$request->mobilenumber;
    	$contacts->officenumber=$request->officenumber;
    	$contacts->website=$request->website;

    	$contacts->save();

    	$contact=Contact::all();

    	return view('Admin.Contact.index')->with('contact', $contact);
    }
    public function edit($id){
    	$concat=Contact::find($id);
    	return view('Admin.Contact.edit')->with('contacts', $concat);
    }
    public function update(Request $request , $id){
    	$contacts=Contact::find($id);

    	$contacts->name=$request->input('name');
    	$contacts->address=$request->input('address');
    	$contacts->zipcode=$request->input('zipcode');
    	$contacts->postboxnumber=$request->input('postboxnumber');
    	$contacts->pannumber=$request->input('pannumber');
    	$contacts->mobilenumber=$request->input('mobilenumber');
    	$contacts->officenumber=$request->input('officenumber');
    	$contacts->website=$request->input('website');

    	$contacts->save();

    	$contact=Contact::all();

    	return view('Admin.Contact.index')->with('contact', $contact);
    }
    public function destroy($id){
    	$contact = Contact::find($id);

        $contact->delete();

       $contact=Contact::all();

    	return view('Admin.Contact.index')->with('contact', $contact);
    }
}

resources/views/Admin/Contact/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/Contact/create.blade.php
@extends('Admin.Contact.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE CONTACT INFORMATION </h1>
		</div>
	</div>

<form class="form" action="{{route('Contact.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Name</label>
			<input type="text" name="name" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Address</label>
			<input type="text" name="address" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Zip Code</label>
			<input type="text" name="zipcode" class="form-control" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Post Box Number</label>
			<input type="text" name="postboxnumber" class="form-control" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Pan Number</label>
			<input type="text" name="pannumber" class="form-control" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Mobile Number</label>
			<input type="text" name="mobilenumber" class="form-control" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Office Number</label>
			<input type="text" name="officenumber" class="form-control" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Website</label>
			<input type="text" name="website" class="form-control" required>
		<div class="help-block"></div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Contact/edit.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT CONTACT INFORMATION </h1>
		</div>
	</div>

<form class="form" action="{{route('Contact.update', [$contacts->id])}} " method="POST" enctype="multipart/form-data">
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Name</label>
			<input type="text" name="name" class="form-control" value="{{$contacts->name}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Address</label>
			<input type="text" name="address" class="form-control" value="{{$contacts->address}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Zip Code</label>
			<input type="text" name="zipcode" class="form-control" value="{{$contacts->zipcode}}"  required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Post Box Number</label>
			<input type="text" name="postboxnumber" class="form-control" value="{{$contacts->postboxnumber}}" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Pan Number</label>
			<input type="text" name="pannumber" class="form-control" value="{{$contacts->pannumber}}" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Mobile Number</label>
			<input type="text" name="mobilenumber" class="form-control" value="{{$contacts->mobilenumber}}" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Office Number</label>
			<input type="text" name="officenumber" class="form-control" value="{{$contacts->officenumber}}" required>
		<div class="help-block"></div>
			<div class="form-group">
			<label class="control-label">Website</label>
			<input type="text" name="website" class="form-control" value="{{$contacts->website}}" required>
		<div class="help-block"></div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/Contact/index.blade.php
@extends('Admin.Contact.base')

@section('action-content')


<div class="adminAbout">
	<table class="table">
		@foreach($contact as $contacts)
		<tr>
			<td>Name</td>
			<td>{{$contacts->name}}</td>
		</tr>
		<tr>
			<td>Address</td>
			<td>{{$contacts->address}} </td>
		</tr>
		<tr>
			<td>Zip Code</td>
			<td>{{$contacts->zipcode}} </td>
		</tr>
		<tr>
			<td>Post Box Number</td>
			<td>{{$contacts->postboxnumber}}</td>
		</tr>
		<tr>
			<td>Pan Number</td>
			<td>{{$contacts->pannumber}}</td>
		</tr>
		<tr>
			<td>Mobile Number</td>
			<td>{{$contacts->mobilenumber}}</td>
		</tr>
		<tr>
			<td>Office Number</td>
			<td>{{$contacts->officenumber}}</td>
		</tr>
		<tr>
			<td>Website</td>
			<td>{{$contacts->website}}</td>
		</tr>
		<tr>
			<td><a href="{{route('Contact.edit', $contacts->id)}}"  class="btn btn-success">Edit</a></td>
			<td>


<form action="{{route('Contact.destroy', [$contacts->id])}}" method="POST">
    		<input type="hidden" name="_method" value="DELETE">
   		<input type="hidden" name="_token" value="{{ csrf_token() }}">
   		<input type="submit" class="btn btn-danger" value="Delete"/>
</form>

			@endforeach
			@if($contact->isEmpty())
			<td><a href="{{route('Contact.create')}}"  class="btn btn-primary">Create</a></td>
			@else
			
			@endif
			
		</tr>
		
	</table>
</div>

@endsection