routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');

Route::get('/admin', function(){
	return view('Admin.index');
});
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController');
Route::resource('Admin/ProjectList','Admin\ProjectListController');
Route::resource('Admin/Services','Admin\ServicesController');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController');
Route::resource('Admin/Contact','Admin\ContactController');
Route::resource('Admin/Gallary','Admin\GallaryController');
Route::resource('Admin/MyCline','Admin\ContactUserController');
 

app/Http/Controllers/Admin/ProjectListController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\ProjectList;
use Image;
use DB;
class ProjectListController extends Controller
{
    public function index(){
    	$ProjectLists=ProjectList::all();

       return view('Admin.ProjectList.index')->with('ProjectList',$ProjectLists);
    }
    public function create(){
    	return view('Admin.ProjectList.create');
    }
    public function store(Request $request){
    	$ProjectList =new ProjectList;

    	$ProjectList->category=$request->category;
    	$ProjectList->subcategory=$request->subcategory;
    	$ProjectList->projectTitle=$request->projectTitle;
    	$ProjectList->description=$request->description;

    		if ($request->hasFile('coverImage')) {

            $file=$request->file('coverImage');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $ProjectList->coverImage=$file_name;
        }

    		if ($request->hasFile('file')) {

            $file=$request->file('file');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            $file->move($location, $file_name);
            $ProjectList->file=$file_name;
        }
        $ProjectList->save();
       
       $ProjectLists=ProjectList::all();

       return view('Admin.ProjectList.index')->with('ProjectList',$ProjectLists);

    }
    public function show($id){

    	$project= DB::table('project_lists')->find($id);

    	return view('Admin.ProjectList.show')->with('projects', $project);
    }
    public function edit($id){
    	$projects= DB::table('project_lists')->find($id);

    	return view('Admin.ProjectList.edit')->with('project', $projects);
    }
    public function update(Request $request, $id){

    	$updateData=ProjectList::find($id);

    	$updateData->category=$request->input('category');
    	$updateData->subcategory=$request->input('subcategory');
    	$updateData->projectTitle=$request->input('projectTitle');
    	$updateData->description=$request->input('description');


    		if ($request->hasFile('coverImage')) {

            $file=$request->file('coverImage');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $updateData->coverImage=$file_name;
        }

    		if ($request->hasFile('file')) {

            $file=$request->file('file');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            $file->move($location, $file_name);
            $updateData->file=$file_name;
        }

        $updateData->save();
         $ProjectLists=ProjectList::all();

       return view('Admin.ProjectList.index')->with('ProjectList',$ProjectLists);
    }
    public function destroy($id)
    {
        $project = ProjectList::find($id);

        $project->delete();

       $ProjectLists=ProjectList::all();

       return view('Admin.ProjectList.index')->with('ProjectList',$ProjectLists);
    }
}

resources/views/Admin/ProjectList/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/ProjectList/create.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE PROJECT </h1>
		</div>
	</div>

<form class="form" action="{{route('ProjectList.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Project Title</label>
			<input type="text" name="projectTitle" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Category</label>
			<input type="text" name="category" class="form-control" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Sub Catrgory</label>
			<input type="text" name="subcategory" class="form-control" required>
		<div class="help-block"></div>
		<div class="form-group">
			<spam>Description</spam>
			<textarea name="description" class="form-control" id="description" required></textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Cover Image</label>
			<input type="file" name="coverImage" class="form-control" required>
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">File</label>
			<input type="file" name="file" class="form-control" required>
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/ProjectList/edit.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT PROJECT </h1>
		</div>
	</div>

<form class="form" action="{{route('ProjectList.update', [$project->id])}} " method="POST" enctype="multipart/form-data">
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Project Title</label>
			<input type="text" name="projectTitle" class="form-control" value="{{$project->projectTitle}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Category</label>
			<input type="text" name="category" class="form-control" value="{{$project->category}}" required>
		<div class="help-block"></div>
				<div class="form-group">
			<label class="control-label">Sub Catrgory</label>
			<input type="text" name="subcategory" class="form-control" value="{{$project->subcategory}}" required>
		<div class="help-block"></div>
		<div class="form-group">
			<spam>Description</spam>
			<textarea name="description" class="form-control" id="description" required>
				{{$project->description}}
			</textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Cover Image</label>
			<?php $url=url('image/'.$project->coverImage); 
                                ?>
			<input type="file" name="coverImage" class="form-control" value="{{$project->coverImage}}" >
			<img src="{{$url}}" height="100px" width="100px">
		<div class="help-block"></div>
		</div>
	</div>
			<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">File</label>
			<input type="file" name="file" class="form-control" value="{{$project->file}}">
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>

@endsection

resources/views/Admin/ProjectList/index.blade.php
@extends('Admin.About.base')

@section('action-content')
<div class="row">
	<div class="col-lg-12">
		<table class="table">
			<tr>
				<td>Sn</td>
				<td>Project Name</td>
				<td>Action</td>
				<td>
					<a href="{{route('ProjectList.create')}}"  class="btn btn-primary btn-xm">Create</a>
				</td>
			</tr>
			@foreach($ProjectList as $ProjectLists)
			<tr>

				<td>{{$ProjectLists->id}}</td>
				<td>{{$ProjectLists->projectTitle}}</td>
				<td><a href="{{route('ProjectList.show',$ProjectLists->id )}}" class="btn btn-outline-info btn-sm" style="margin-right: 20px;">View</a>
					<a href="{{route('ProjectList.edit',$ProjectLists->id )}}" class="btn btn-outline-success btn-sm" style="margin-right: 20px;">Edit</a>
				</td>
			</tr>
			@endforeach
		</table>
	</div>
	
</div>

@endsection

resources/views/Admin/ProjectList/show.blade.php
@extends('Admin.About.base')

@section('action-content')

<div class="adminAbout">
	<table class="table">
		<tr>
			<td>Name</td>
			<td>{{$projects->projectTitle}}</td>
		</tr>
			<td>Project Category</td>
			<td>{{$projects->category}}</td>
		</tr>
			<td>Project Sub Category</td>
			<td>{{$projects->subcategory}}</td>
		</tr>
		<tr>
			<td>Description</td>
			<td>{!!$projects->description!!} </td>
		</tr>
				<tr>
			<td>Cover Image</td>
			<?php $url=url('image/'.$projects->coverImage); 
                                ?>
			<td> <img src="{{$url}}" height="200px" width="200px"></td>
		</tr>
		<tr>
			<td><a href="{{route('ProjectList.edit', $projects->id)}}"  class="btn btn-success">Edit</a></td>
			<td>


<form action="{{route('ProjectList.destroy', [$projects->id])}}" method="POST">
    		<input type="hidden" name="_method" value="DELETE">
   		<input type="hidden" name="_token" value="{{ csrf_token() }}">
   		<input type="submit" class="btn btn-danger" value="Delete"/>
</form>
			
		</tr>
		
	</table>
</div>
@endsection