routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\SiteController@aboutIndex')->name('home');

Route::get('/admin', function(){
	return view('Admin.index');
});
//Admin Route Hear

Route::resource('Admin/About','Admin\AboutController');
Route::resource('Admin/ProjectList','Admin\ProjectListController');
Route::resource('Admin/Services','Admin\ServicesController');
Route::resource('Admin/SocialMedia','Admin\ScialMediaController');
Route::resource('Admin/Contact','Admin\ContactController');
Route::resource('Admin/Gallary','Admin\GallaryController');
Route::resource('Admin/MyCline','Admin\ContactUserController');
 

app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\About;
use Image;

class AboutController extends Controller
{
    public function index(){
    	$abouts=About::all();
    	return view('Admin.About.index')
    	->with('about',$abouts);
    }
    public function create(){
    	return view('Admin.About.create');
    }
    public function store(Request $request){

    	$abouts= new About;
    	$abouts->name=$request->name;
    	$abouts->description=$request->description;

   		if ($request->hasFile('photo')) {

            $file=$request->file('photo');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $abouts->photo=$file_name;
        }
        $abouts->save();

    	    	$abouts=About::all();
    	return view('Admin.About.index')
    	->with('about',$abouts)
    	->with('success','You have successfully add about.');
    }
   public function edit($id){

   	$about=About::find($id);
   	return view('Admin.About.edit')->with('about', $about);
   }
   public function update(Request $request, $id){
   	$updateData=About::find($id);
   	$updateData->name=$request->input('name');
   	$updateData->description=$request->input('description');

   	   	if ($request->hasFile('photo')) {

            $file=$request->file('photo');
            $file_name=time().'.'. $file->getClientOriginalExtension();
            $location=('image/' .$file_name);
            Image::make($file)->resize(1500, 1500)->save($location);
            $updateData->photo=$file_name;
        }
     	$updateData->save();

    	    	$abouts=About::all();
    	return view('Admin.About.index')
    	->with('about',$abouts)
    	->with('success','You have successfully add about.');
   }
       public function destroy($id)
    {
        $about = About::find($id);

        $about->delete();

        $abouts=About::all();
    	return view('Admin.About.index')
    	->with('about',$abouts);
    }
}

resources/views/Admin/About/base.blade.php
@extends('Admin.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/Admin/About/create.blade.php
@extends('Admin.About.base')

@section('action-content')
<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>CREATE ABOUT </h1>
		</div>
	</div>

<form class="form" action="{{route('About.store')}} " method="POST" enctype="multipart/form-data">
	  @csrf

	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Name</label>
			<input type="text" name="name" class="form-control" required>
		<div class="help-block"></div>
		<div class="form-group">
			<spam>Description</spam>
			<textarea name="description" class="form-control" id="description" required></textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Photo</label>
			<input type="file" name="photo" class="form-control" required>
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div> 
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/Admin/About/edit.blade.php
@extends('Admin.About.base')

@section('action-content')
<div class="createStyle">
	<div class="row">
		<div class="col-sm-12">
			<h1>EDIT ABOUT </h1>
		</div>
	</div>

	<form action="{{route('About.update', [$about->id])}}" method="POST">
	  
	   <input type="hidden" name="_method" value="PUT">
	  {{ csrf_field() }}
	<div class="row">
		<div class="col-sm-12">
		<div class="form-group">
			<label class="control-label">Name</label>
			<input type="text" name="name" value="{{$about->name}}" class="form-control" required>
		<div class="help-block"></div>
		<div class="form-group">
			<label class="control-label">Description</label>
			<textarea name="description" class="form-control" id="description" required>{{$about->description}}</textarea>
		<div class="help-block"></div>
	</div>
</div>
</div>
		<div class="col-sm-12">
			<div class="form-group">
			<label class="control-label">Photo</label>
			<?php $url=url('image/'.$about->photo); 
                                ?>
			<input type="file" name="photo" class="form-control" value="{{$about->photo}}" >
			<img src="{{$url}}" height="100px" width="100px">
		<div class="help-block"></div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
			<button class="btn btn-success" type="submit">Save</button>
		<div class="help-block"></div>
		</div>
	</div>
</form>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection

resources/views/Admin/About/index.blade.php
@extends('Admin.About.base')

@section('action-content')


<div class="adminAbout">
	<table class="table">
		@foreach($about as $abouts)
		<tr>
			<td>Name</td>
			<td>{{$abouts->name}}</td>
		</tr>
		<tr>
			<td>Description</td>
			<td>{!!$abouts->description!!} </td>
		</tr>
				<tr>
			<td>Photo</td>
			<?php $url=url('image/'.$abouts->photo); 
                                ?>
			<td> <img src="{{$url}}" height="200px" width="200px"></td>
		</tr>
		<tr>
			<td><a href="{{route('About.edit', $abouts->id)}}"  class="btn btn-success">Edit</a></td>
			<td>


<form action="{{route('About.destroy', [$abouts->id])}}" method="POST">
    		<input type="hidden" name="_method" value="DELETE">
   		<input type="hidden" name="_token" value="{{ csrf_token() }}">
   		<input type="submit" class="btn btn-danger" value="Delete"/>
</form>

			@endforeach
			@if($about->isEmpty())
			<td><a href="{{route('About.create')}}"  class="btn btn-primary">Create</a></td>
			@else
			
			@endif
			
		</tr>
		
	</table>
</div>

@endsection